CREATE OR REPLACE PROCEDURE DEVELOPMENT.SUBSIDIARY.SPEMPLOYEERECORD()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT INTO DEVELOPMENT.SUBSIDIARY.GLEN VALUES(4,'JOSH','KIMMEL');
    RETURN 'SUCCESS';
END;
$$;