CREATE OR REPLACE PROCEDURE PRODUCTION.COMPANY.SPCOMPANYRECORD()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''LIFESCIENCES'',20);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''TECHNOLOGY'',30);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''HOA'',50);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''HOTEL'',70);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''BANKING'',60);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''SERVICES'',90);
    RETURN ''SUCCESS'';
END;
';