CREATE OR REPLACE TABLE PRODUCTION.COMPANY.COMPANY_NAME(
NAME VARCHAR,
EMPLOYEECOUNT NUMBER
); 

CREATE OR REPLACE PROCEDURE PRODUCTION.COMPANY.SPCOMPANYRECORD()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''LIFESCIENCES'',20);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''TECHNOLOGY'',30);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''HOA'',50);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''HOTEL'',70);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''BANKING'',60);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''SERVICES'',90);
    INSERT INTO PRODUCTION.COMPANY.COMPANY_NAME VALUES(''TELECOM'',100);
    COMMIT;
    RETURN ''SUCCESS'';
END;
';

CALL PRODUCTION.COMPANY.SPCOMPANYRECORD();